### ISSUE TITLE
Not Working on GL-MT300N

### ISSUE THREAD

**Issue by zischwartz** [sebpiq/FreedomPortal#3]
This is a really cool project!

I'm trying to run it on a [`GL-MT300N`](https://wiki.openwrt.org/toh/gl-inet/gl.inet_gl-mt300n_v1). I used the web interface to connect to the internet, upgrade the firmware to 2.25, and am able to `ssh` in.

However, my distribution seems to differ from what you're running. `uhttpd` for instance isn't present. Following the rest of the README.md appears to work, but when the router restarts, I'm not able to connect to it, and have to connect over ethernet and reload the firmware in failsafe mode.

It'd be helpful to know what devices you're using to develop this and what else it works on.  Links to the binaries used would be awesome too.

Thanks!

**Comment by sebpiq** [comment]
Hi @zischwartz !

Yes, sorry the project is very new and the instructions are by no means exhaustive. And there will surely be some bugs too. I use the `GL-AR150` ! I will add that to the docs ... A collaborator of mine had managed to install this on the `GL-MT300N`, so I think it should work as well! 

I think if you don't manage to connect to your router through wifi after the instructions in the README it might be because of the modifications in `/etc/config/dhcp` and `/etc/config/firewall` files. 
For debugging purpose, I recommend to follow the instructions until "Redirect all requests to the app" and stop before that! Then reboot your router, and at this stage, though requests won't be redirected to the captive portal as they normally should, at least your content should be served at [192.168.8.1](http://192.168.8.1). Let's see first if that works properly, and if yes we can move on to next step and I'll try to debug it with you ...

Also which "binaries" are you talking about?

**Comment by sebpiq** [comment]
no answer, so I am closing this ...
