### ISSUE TITLE
Easier and centralized config 

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/FreedomPortal#4]
Config is by now spread around in several files (lighttpd, sh scripts, lua scripts, etc ...) it should be centralized in one file.

**Comment by sjbowen** [comment]
Would it be possible to make the domains used in redirects part of the centralised config file, i.e.  alternative domains to use instead of freedomportal.com or nofreedom.com?

A possible scenario is when the user refreshes a FreedomPortal-served web page later, when connected to the Internet via other means. Looking for pages on freedomportal.com or nofreedom.com often redirects to domain registration service, where it may be better to allow the developer to ensure that relevant live domains/websites are used instead?

**Comment by sebpiq** [comment]
@sjbowen  Sure! This is one of the parameters I want to be able to configure too :)

**Comment by sjbowen** [comment]
This would also help with an issue I encountered on an Android LG phone - on connecting to the hotspot the phone reports that the hotspot has no Internet connectivity and asks the user whether they wish to use their mobile data network in addition.

**Comment by sebpiq** [comment]
@sjbowen how would it help with this?

**Comment by sjbowen** [comment]
Sorry, @sebpiq, I should have been clearer. If the LG user accepts the prompt to use mobile data, the phone both connects to the FreedomPortal and returns the live webpage for http://www.freedomportal.com/ rather than content on the router. So, being able to specify the domain used would ensure a failsafe that the user could be redirected to a relevant website.

**Comment by sjbowen** [comment]
Hi @sebpiq, I'm going to deploy a FreedomPortal soon and would like to change the domains used in the redirects from Freedomportal.com / nofreedom.com to something else. Assuming you don't have time to do the centralised config now, please would you tell me where I can change these domains in the existing config structure. Thanks!

**Comment by sebpiq** [comment]
Hi Simon!
Actually I have time! I was about to do it in the next couple of weeks. Is that soon enough for you?

**Comment by sjbowen** [comment]
Brilliant! In the next two weeks is fine. I've noticed one or two slight problems accessing FreedomPortal from different phones. I can make a list and add as an issue(s), if helpful?

**Comment by sebpiq** [comment]
sure! Would definitely be helpful! Also, I am planning to drop the support for full-browser instead of CNA. There are too many issues with it, and apparently it doesn't work on later iOS ... has the CNA been working for you in the end?

**Comment by sjbowen** [comment]
Ha! The issue was just that - full-browser mode not working on iOS 10.3.1, and being rather difficult to use on Android. CNA mode isn't ideal - it takes up some screen space I'd like to use for full-screen images, and it sticks with portrait orientation. But I can live with it if it resolves some of the other issues working in full-browser mode. 

In some cases, It would be nice to be able to use CNA and to be able to open pages in a full browser too - e.g. where you have access to configure the device, such as it being part of an exhibition. But I recognise that isn't really the intention for FreedomPortal (just me trying to use one thing for something else...)

**Comment by sebpiq** [comment]
In any case, the CNA mode allows pages to be opened in full-browser! 
The difference is that in full-browser mode, the CNA was following a protocol to push the phone towards a full browser rather than displaying the page in CNA.

**Comment by sebpiq** [comment]
@sjbowen this is now done, new code is in the repository master branch and instructions have been updated
